[package]
name = "the_nonhumankind"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.9.0"
termion = "1.5.6"
rand = "0.8.5"



[[example]]
name = "basic_simulation"
path = "examples/basic_simulation.rs"
